[package]
name = "edo"
version = "0.1.0"
edition = "2024"
authors = ["Jarrett Tierney <jmt@amazon.com>"]
repository = "https://github.com/awslabs/edo"
license = "MIT OR Apache-2.0"
keywords = ["edo"]

[dependencies]
astral-tokio-tar  = { workspace = true }
async-compression = { workspace = true }
clap              = { workspace = true }
snafu             = { workspace = true }
tokio             = { workspace = true }
tracing           = { workspace = true }
edo-core          = { path = "../edo-core" }
